version: '3.7'

#Instancias equivalenetes รก m5.large

services:

  for-test:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
      args:
        EXECUTABLE_CLASS: ForPerformanceTestApplication
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G

  flatmap-test:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
      args:
        EXECUTABLE_CLASS: LambdaPerformanceTestApplication
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G